name: Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Build 
        run: npm run build
